import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/main.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{'display': 'flex', 'flexDirection':'column'}} >
          <nav style={{'minHeight': '72px'}} ></nav>
          <div style={{'display': 'flex'}} >
            <aside style={{'maxWidth': '360px', 'width': '100%'}} >
            </aside>
            <section style={{'paddingLeft': '46px', 'paddingRight': '76px', 'width': '100%'}} >
              {children}
            </section>
          </div>
        </div>
      </body>
    </html>
  )
}
