import type { Metadata } from 'next'
import 'styles'
import { FC, ReactNode } from "react";

export const metadata: Metadata = {
  title: 'Dali',
  description: 'Generated by create next app',
}

type Props = {
  children: ReactNode
}

const LogInLayout: FC<Props> = (props) => {
  const { children } = props

  return (
    <html lang="es">
      <body>
        {children}
      </body>
    </html>
  )
}

export default LogInLayout
